# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    param_fetcher_listener: true
    view:
        empty_content: 200
        view_response_listener:  true # Devolver entidades y serializarlos antes
        failed_validation: HTTP_BAD_REQUEST
        formats:
            json: true
            xml: false
    body_listener:
        decoders:
            json: fos_rest.decoder.json # Llegan json y los descondificamos
    format_listener:
        rules: # De esta manera si queremos un admin fos_rest lo ignora
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true, fallback_format: html }
    exception:
        enabled: true
    serializer: # Devolver propiedades con NULL
        serialize_null: true